# Generated by Django 5.1.6 on 2025-03-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.especialidade'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=6),
        ),
    ]
